#!/usr/bin/perl

my ($what, @args) = @ARGV;

_usage() unless defined $what;

$what =~ tr/-/_/;

if (defined &$what) { print $what->(@args), "\n" }
else {
    _usage($what);
}

sub current_branch_name {
  _run("git rev-parse --symbolic-full-name --abbrev-ref HEAD");
}

sub branch_remote {
  my ($branch) = @_;
  $branch ||= current_branch_name();
  _run("git config --get 'branch.$branch.remote'");
}

sub working_tree_dirty {
  my ($arg) = @_;
  for my $cmd ("git rev-parse --verify HEAD > /dev/null",
	       "git update-index --ignore-submodules --refresh > /dev/null",
	       "git diff-files --quiet --ignore-submodules",
	       "git diff-index --cached --quiet HEAD --ignore-submodules") {
      system($cmd) == 0 or return 1;
  }
  return 0;
}

sub _run {
  my @cmd = @_;
  open my($p), "-|", @cmd or die "Couldn't run '@cmd': $!";
  my $res = join "", <$p>;
  chomp($res);
  return $res;
}

sub _usage {
  my ($what) = @_;
  warn "Don't know how to get '$what'; try:\n" if defined $what;
  my @names = sort grep !/^_/ && defined &{$_}, keys %main::;
  tr/_/-/ for @names;
  print STDERR join "\n", @names, "";
  exit;
}
